version: '3.0'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/pg/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rewards-mvp
    command: flask run --host 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 5002:5000